"""Initial migration for SQLite

Revision ID: b412c43c6cbb
Revises: 
Create Date: 2025-07-30 18:06:27.638868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b412c43c6cbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=288),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=288),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('language')

    # ### end Alembic commands ###
